[package]
name = "bwa"
version = "0.1.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]
build = "build.rs"


[dependencies]
libc = "*"
rust-htslib = { git = "https://github.com/rust-bio/rust-htslib",  rev="1e905704de18" }
failure = "*"
failure_derive = "*"

[build-dependencies]
bindgen = "*"
skeptic = "0.13"
[dev-dependencies]
skeptic = "0.13"
