[package]
name = "bwa"
version = "0.1.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]
build = "build.rs"


[dependencies]
libc = "*"
rust-htslib = "0.19"
failure = "*"
failure_derive = "*"

[build-dependencies]
bindgen = "*"
skeptic = "*"

[dev-dependencies]
skeptic = "*"
