[package]
name = "bwa"
version = "0.1.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]
build = "build.rs"


[dependencies]
libc = "*"
rust-htslib = { version = "^0.21", default-features = false }
failure = "*"
failure_derive = "*"

[build-dependencies]
bindgen = "0.36"
skeptic = "*"

[dev-dependencies]
skeptic = "*"
