[package]
name = "bwa"
version = "0.1.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]
build = "build.rs"


[dependencies]
libc = "*"
failure = "*"
failure_derive = "*"
rust-htslib = { version = "0.34.0", default-features = false, features = ["serde_feature"] }